# Build the deliverable
FROM node:lts-stretch-slim as compile
RUN npm install -g @angular/cli
WORKDIR /app
COPY . .
RUN npm install
RUN ng build --prod

# Get test deliverables 
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable
RUN npm test
